sudo: false
dist: trusty
language: python
python: 3.7-dev

env:
  - PIPENV_IGNORE_VIRTUALENVS=1

addons:
  sonarcloud:
    organization: "cryptic-game"
    token:
      secure: "Q8xUQdcEbAb62dvegXg0362wycmG09R7L4qJKTvu4460ZBF8WHjO6PHGViEI0JebxEE2LfRSJSheHs1NtlTf94z8GLFBd5/HVT/PpCHgRGU5mtNeWcy4i/i/SOugQ4D+c5cRKp+nZJIsjN9yqhiOmWFyPQXNAIR9O3V9qLS9rHxl8SUx7VM6GqQRPRYwhlFFTYU57sW1KwJ7s0d/NMJe/mn2I9V9WsDpeISEyt4/Fo2XkTLOFyrKvRiQ+zi/hGZf1xE2tiJuT5uZ7WBavizYZTAnUlIhWwK2gMSTgQAEdn2bvXTyP1/Tg/HUmr77qn2vX2rBdB8txHQQwrxU2pYZmvQa/Q1Mrga6IQ6PvR02lvVhXPJmpfxGEc+dn0BnslSysH3d/cpmPNqbUfJDatjzVL4ik+JwWVhB/uUJ7DIXDxYv5oYrA1IJIaKHs7v6clx1S07SQ/N7FRe6zBuo5cEmZYdS9hrzp17WZGt9jd6BRgLh87widOTBZKF34DmoHjCmjtmVQX9XTdP8byjk6QvQqKyyZuXCbXOzryPBCLsPKm77BUoJTJSAQKzoc0Kzkv0x7NX2/e/3xSoH8O/N7Eg+fCiGjpqKhTolSjHpQx4z5YGId2pfRR8s66dS3lON8CwLt+FkI66BGP0pb1URsdOqBQs0XhxTqtBEiVh/R2/iwuA="

install:
  - cd app/ && pip install pipenv && pipenv sync --dev
script:
  - pipenv run coverage
  - cd .. && sonar-scanner
